export const API_BASE_URL = 'http://localhost:8080/api'
export const BASE_URL = 'http://localhost:8080/api'
export const NOTIFICATION_HUB = 'http://localhost:8080'
export const VITE_APP_GOONG_API_KEY = '9hI3nUIhxsu9GxxA97L7RjF2OlIHVjJxEgxqZ1C3'
export const VITE_APP_GOONG_MAP_KEY = 'ZdlDGQqjlNt3AKAYCbl7gbD3jwc8gmU96fm7vu5D'
